services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legal-ai-frontend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_oNhiQsanu4p2@ep-broad-mountain-aftyry8d.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require"
      AI_SERVICE_URL: http://ai_service:5001
      NODE_ENV: production
      WARMUP_ON_START: "true"
    volumes:
      - ./Legal_docs:/app/Legal_docs:ro
    depends_on:
      - ai_service
    restart: unless-stopped
    networks:
      - legal-ai-network

  ai_service:
    build:
      context: ./ai_service
    container_name: legal-ai-service
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production
      OLLAMA_HOST: host.docker.internal:11434
      WARMUP_ON_START: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - legal-ai-network

networks:
  legal-ai-network:
    driver: bridge
