version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legal-ai-frontend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:pass123@legal-ai-db:5432/legal_ai_db}
      AI_SERVICE_URL: http://ai_service:5001
    volumes:
      - ./Legal_docs:/app/Legal_docs:ro
    depends_on:
      - ai_service
      - legal-ai-db
    restart: unless-stopped
    networks:
      - legal-ai-network

  ai_service:
    build:
      context: ./ai_service
    container_name: legal-ai-service
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production
      OLLAMA_HOST: host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - legal-ai-network

  legal-ai-db:
    image: postgres:15
    container_name: legal-ai-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: legal_ai_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - legal-ai-network

networks:
  legal-ai-network:
    driver: bridge

volumes:
  pg_data:
