services:
  ollama1:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_THREADS=4
  ollama2:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_NUM_THREADS=4
  ollama3:
    image: ollama/ollama:latest
    ports:
      - "11436:11434"
    environment:
      - OLLAMA_NUM_THREADS=4
  ollama4:
    image: ollama/ollama:latest
    ports:
      - "11437:11434"
    environment:
      - OLLAMA_NUM_THREADS=4
  ai_service:
    build: ./ai_service
    ports:
      - "5002:5001"
    environment:
      - OLLAMA_HOSTS=http://ollama1:11434,http://ollama2:11434,http://ollama3:11434,http://ollama4:11434
      - DATABASE_URL=postgresql://neondb_owner:npg_oNhiQsanu4p2@ep-broad-mountain-aftyry8d.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require
      - PGDATABASE=neondb
      - PGHOST=ep-broad-mountain-aftyry8d.c-2.us-west-2.aws.neon.tech
      - PGPORT=5432
      - PGUSER=neondb_owner
      - PGPASSWORD=npg_oNhiQsanu4p2
    depends_on:
      - ollama1
      - ollama2
      - ollama3
      - ollama4
    networks:
      - backendnet
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_oNhiQsanu4p2@ep-broad-mountain-aftyry8d.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require
      - PGDATABASE=neondb
      - PGHOST=ep-broad-mountain-aftyry8d.c-2.us-west-2.aws.neon.tech
      - PGPORT=5432
      - PGUSER=neondb_owner
      - PGPASSWORD=npg_oNhiQsanu4p2
    depends_on:
      - ai_service
    networks:
      - backendnet
networks:
  backendnet:
    driver: bridge 